apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    app: webapp
spec:
  containers:
  - name: webapp-color
    image: asrafbd/webapp-color:v2
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: pink

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
  type: LoadBalancer
